name: task_management
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  ionicons: 0.1.2
  flutter: 
    sdk: flutter
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

