// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAteYZREsPsxd54XfcQEdUuZswf_r9GdXY',
    appId: '1:118275501665:web:b2caccf44baa253945c420',
    messagingSenderId: '118275501665',
    projectId: 'task-management-app-49b9c',
    authDomain: 'task-management-app-49b9c.firebaseapp.com',
    storageBucket: 'task-management-app-49b9c.appspot.com',
    measurementId: 'G-LKVDC9V81E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBriUuU4FdQG3JvP65BJaTKcp61A_FFdMc',
    appId: '1:118275501665:android:6c4fc0a95417815745c420',
    messagingSenderId: '118275501665',
    projectId: 'task-management-app-49b9c',
    storageBucket: 'task-management-app-49b9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ4ALAyIsBhZCKcI7dFuO6w0OSnhFkw68',
    appId: '1:118275501665:ios:8f3ecfc074d26a1945c420',
    messagingSenderId: '118275501665',
    projectId: 'task-management-app-49b9c',
    storageBucket: 'task-management-app-49b9c.appspot.com',
    androidClientId: '118275501665-d2a7tck504vgi58kc19436jpi65tohej.apps.googleusercontent.com',
    iosClientId: '118275501665-nj4mthb2rde390calcrrj4p9la3gecgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ4ALAyIsBhZCKcI7dFuO6w0OSnhFkw68',
    appId: '1:118275501665:ios:8f3ecfc074d26a1945c420',
    messagingSenderId: '118275501665',
    projectId: 'task-management-app-49b9c',
    storageBucket: 'task-management-app-49b9c.appspot.com',
    androidClientId: '118275501665-d2a7tck504vgi58kc19436jpi65tohej.apps.googleusercontent.com',
    iosClientId: '118275501665-nj4mthb2rde390calcrrj4p9la3gecgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagement',
  );
}
